services:
  # Django app
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - django_redis
      - django_db

  # Redis (First, run django_redis and the run django)
  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - 6379:6379

  # Database PosgreSQL
  django_db:
    image: postgres
    container_name: postgresql # Host
    restart: always # In case of an error, the database will be restarted to always have it available
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/posgresql

  # pgAdmin DBMS
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 80:80
    depends_on:
      - django_db

  # Celery
  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    ports:
      - 8001:8001
    depends_on:
      - django_redis
      - django_db

  # Celery Beat
  celery_beat: 
    container_name: blog_celery_beat
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    ports:
      - 8002:8002
    depends_on:
      - django_redis
      - django_db
